ALTER TABLE  objective
ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT FALSE;

ALTER TABLE objective
ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE objective
ADD COLUMN IF NOT EXISTS validation TEXT;
