EXTENSION IF NOT EXISTS "UUID_OSSP";

CREATE TABLE IF NOT EXISTS user_achievement(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    achievement_id UUID NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


